import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:mergelings/services/audio_service.dart';

/// The sound effects are generated by `tool/generate_sfx.dart`. These checks
/// catch the two ways that can silently go wrong: a missing file, and a file
/// that exists but is silent or clipped.
void main() {
  test('every Sfx cue has a matching asset declared in pubspec', () {
    final String pubspec = File('pubspec.yaml').readAsStringSync();
    expect(pubspec, contains('assets/audio/'));

    for (final Sfx sfx in Sfx.values) {
      final File file = File('assets/${sfx.asset}');
      expect(file.existsSync(), isTrue, reason: 'missing ${sfx.asset}');
      expect(file.lengthSync(), greaterThan(1000), reason: sfx.asset);
    }
  });

  test('cue volumes stay inside a sane range', () {
    for (final Sfx sfx in Sfx.values) {
      expect(sfx.volume, greaterThan(0.0), reason: sfx.name);
      expect(sfx.volume, lessThanOrEqualTo(1.0), reason: sfx.name);
    }
  });

  test('each WAV is valid 44.1kHz mono PCM that is audible but not clipped',
      () {
    for (final Sfx sfx in Sfx.values) {
      final Uint8List bytes = File('assets/${sfx.asset}').readAsBytesSync();
      final ByteData view = ByteData.sublistView(bytes);

      expect(String.fromCharCodes(bytes.sublist(0, 4)), 'RIFF', reason: sfx.name);
      expect(String.fromCharCodes(bytes.sublist(8, 12)), 'WAVE', reason: sfx.name);
      expect(view.getUint16(20, Endian.little), 1, reason: '${sfx.name} not PCM');
      expect(view.getUint16(22, Endian.little), 1, reason: '${sfx.name} not mono');
      expect(view.getUint32(24, Endian.little), 44100, reason: sfx.name);
      expect(view.getUint16(34, Endian.little), 16, reason: sfx.name);

      // Samples start at byte 44 for this canonical header layout.
      int peak = 0;
      double sumSquares = 0;
      int count = 0;
      for (int i = 44; i + 1 < bytes.length; i += 2) {
        final int sample = view.getInt16(i, Endian.little);
        peak = peak > sample.abs() ? peak : sample.abs();
        sumSquares += sample * sample;
        count++;
      }
      final double rms = count == 0 ? 0 : (sumSquares / count);

      expect(count, greaterThan(1000), reason: '${sfx.name} too short');
      expect(peak, greaterThan(8000), reason: '${sfx.name} is near-silent');
      expect(peak, lessThan(32767), reason: '${sfx.name} is clipping');
      expect(rms, greaterThan(0), reason: '${sfx.name} is silent');

      // First and last samples near zero, or the cue clicks on playback.
      expect(view.getInt16(44, Endian.little).abs(), lessThan(1500),
          reason: '${sfx.name} clicks on start');
      expect(view.getInt16(bytes.length - 2, Endian.little).abs(), lessThan(1500),
          reason: '${sfx.name} clicks on end');
    }
  });

  // The background track is generated by `tool/generate_music.dart`, which
  // builds it to be genuinely periodic over its loop length rather than faded
  // at the edges. These checks are what stop that quietly regressing — a
  // broken loop is only audible after a full lap, which nobody sits through.
  group('music', () {
    late final List<double> samples = _readSamples(_musicFile);

    test('is valid mono PCM at the rate the generator writes', () {
      expect(_musicFile.existsSync(), isTrue,
          reason: 'run: dart run tool/generate_music.dart');

      final Uint8List bytes = _musicFile.readAsBytesSync();
      final ByteData view = ByteData.sublistView(bytes);

      expect(String.fromCharCodes(bytes.sublist(0, 4)), 'RIFF');
      expect(String.fromCharCodes(bytes.sublist(8, 12)), 'WAVE');
      expect(view.getUint16(20, Endian.little), 1, reason: 'not PCM');
      expect(view.getUint16(22, Endian.little), 1, reason: 'not mono');
      expect(view.getUint32(24, Endian.little), AudioService.musicSampleRate);
      expect(view.getUint16(34, Endian.little), 16);
    });

    test('is exactly one loop long', () {
      // The piece is tuned to a harmonic grid derived from this length, so a
      // file of a different duration is not a trim — it is out of tune with
      // its own loop point.
      expect(
        samples.length,
        AudioService.musicSampleRate * AudioService.musicLoopSeconds,
      );
    });

    test('is audible but not clipped', () {
      double peak = 0;
      double sumSquares = 0;
      for (final double s in samples) {
        peak = math.max(peak, s.abs());
        sumSquares += s * s;
      }
      final double rms = math.sqrt(sumSquares / samples.length);

      expect(peak, greaterThan(.3), reason: 'near-silent');
      expect(peak, lessThan(1.0), reason: 'clipping');
      expect(rms, greaterThan(.05), reason: 'far too quiet to be a bed');
    });

    test('joins to itself with no step bigger than its own waveform', () {
      double worstInternal = 0;
      for (int i = 1; i < samples.length; i++) {
        worstInternal = math.max(worstInternal, (samples[i] - samples[i - 1]).abs());
      }
      final double seam = (samples.first - samples.last).abs();

      // The step from the last sample back round to the first is just another
      // sample-to-sample step. If it is bigger than any step inside the track,
      // the loop point is a discontinuity and it will click once per lap.
      expect(
        seam,
        lessThanOrEqualTo(worstInternal),
        reason: 'seam $seam exceeds worst internal step $worstInternal',
      );
    });

    test('does not fade at the edges', () {
      // A track faded in and out loops without clicking but breathes once per
      // lap, which is the exact effect the generator exists to avoid. Real
      // content at both edges is what distinguishes the two.
      const int quarterSecond = AudioService.musicSampleRate ~/ 4;
      double rmsOf(Iterable<double> window) {
        final List<double> v = window.toList(growable: false);
        double sum = 0;
        for (final double s in v) {
          sum += s * s;
        }
        return math.sqrt(sum / v.length);
      }

      final double head = rmsOf(samples.take(quarterSecond));
      final double tail = rmsOf(samples.skip(samples.length - quarterSecond));
      final double whole = rmsOf(samples);

      expect(head, greaterThan(whole * .5), reason: 'fades in');
      expect(tail, greaterThan(whole * .5), reason: 'fades out');
    });

    test('holds a steady level, so the bed never pumps', () {
      const int window = AudioService.musicSampleRate;
      double quietest = double.infinity;
      double loudest = 0;

      for (int start = 0; start + window <= samples.length; start += window) {
        double sum = 0;
        for (int i = start; i < start + window; i++) {
          sum += samples[i] * samples[i];
        }
        final double rms = math.sqrt(sum / window);
        quietest = math.min(quietest, rms);
        loudest = math.max(loudest, rms);
      }

      // Within 3 dB across the whole lap. Chord swells that did not overlap
      // correctly would show up here as a slow throb.
      expect(loudest / quietest, lessThan(1.41),
          reason: 'level swings from $quietest to $loudest');
    });
  });
}

final File _musicFile = File('assets/${AudioService.musicAsset}');

/// The PCM payload as floats in -1..1.
List<double> _readSamples(File file) {
  final Uint8List bytes = file.readAsBytesSync();
  final ByteData view = ByteData.sublistView(bytes);
  final int count = (bytes.length - 44) ~/ 2;
  return <double>[
    for (int i = 0; i < count; i++)
      view.getInt16(44 + i * 2, Endian.little) / 32768.0,
  ];
}
