include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/l10n/app_localizations*.dart"

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - unnecessary_parenthesis
