// Measures where every creature's ink lands and writes the fit table.
//
// Run with:  flutter test tool/measure_creature_fit.dart
//
// Rerun after any change to creature_painter.dart or a creature spec that
// changes a silhouette. test/creature_fit_test.dart fails when something has
// grown out of its tile, and names this tool.
import 'dart:io';
import 'dart:ui';

import 'package:flutter_test/flutter_test.dart';
import 'package:mergelings/data/creature_spec.dart';
import 'package:mergelings/data/worlds.dart';
import 'package:mergelings/render/creature_painter.dart';

import '../test/support/ink_bounds.dart';

const String kOut = 'lib/render/creature_fits.g.dart';

void main() {
  test('measure creature fit', () async {
    final StringBuffer out = StringBuffer()
      ..writeln(
        '// GENERATED by `flutter test tool/measure_creature_fit.dart`. '
        'Do not edit.',
      )
      ..writeln('//')
      ..writeln('// Each entry: scale, sideways shift. See CreatureFit.')
      ..writeln("import 'creature_fit.dart';")
      ..writeln()
      ..writeln('const Map<String, CreatureFit> kCreatureFits =')
      ..writeln('    <String, CreatureFit>{');

    for (final World world in kWorlds) {
      for (final CreatureSpec spec in world.creatures) {
        final Rect raw = await measureInk(spec, fit: CreatureFit.raw);
        final CreatureFit fit = fitFromInk(raw);
        out.writeln("  '${spec.id}': CreatureFit(${fit.scale}, ${fit.dx}),");
        // ignore: avoid_print
        print(
          '${spec.id}  ink ${raw.left.toStringAsFixed(3)}..'
          '${raw.right.toStringAsFixed(3)} x '
          '${raw.top.toStringAsFixed(3)}..${raw.bottom.toStringAsFixed(3)}'
          '  -> scale ${fit.scale} dx ${fit.dx}',
        );
      }
    }
    out.writeln('};');
    File(kOut).writeAsStringSync(out.toString());
  });
}
